spring.application.name=ss6_project_quiz


spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ss6_project_quiz?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:ad1412}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}

spring.messages.encoding=UTF-8

spring.security.oauth2.client.registration.google.client-id=1064579979804-qv0umjo4pqo7o50mek0rgpchu7ic6tmm.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}